AB#39 adding logs to the UserCommandService framework layer
Ramir0/cqrs-user-service pull request #10
Opened 2023-08-25 16:02 UTC by huascraft

I added the four levels of logs that we are using to the framework layer in usercomanservice

2023-09-04 16:17 UTC, Ramir0 requested changes

2023-09-04 16:17 UTC, Ramir0 commented on cqrs-user-command-service/src/main/java/dev/amir/usercommand/framework/output/sql/adapter/UserOutputAdapter.java
> +            log.info("Eliminating user");
Replace `Eliminating` with `Deleting`

2023-09-13 15:16 UTC, Ramir0 commented on cqrs-user-command-service/src/main/java/dev/amir/usercommand/framework/output/sql/adapter/UserOutputAdapter.java
> +            log.info("Eliminating user");
@huascraft could you fix this?

2023-09-13 15:58 UTC, huascraft commented on cqrs-user-command-service/src/main/java/dev/amir/usercommand/framework/output/sql/adapter/UserOutputAdapter.java
> +            log.info("Eliminating user");
done

2023-09-13 16:54 UTC, Ramir0 requested changes

2023-09-13 16:54 UTC, Ramir0 commented on cqrs-user-command-service/src/main/java/dev/amir/usercommand/framework/input/rest/controller/UserController.java
> +            log.error("Error updating user with ID {}: {}", id, e.getMessage(), e);
.getMessage() is not needed

2023-09-16 18:33 UTC, Ramir0 approved these changes

2023-09-17 14:09 UTC, merged