AB#3 setup readme file
Ramir0/cqrs-user-service pull request #6
Opened 2023-08-16 17:28 UTC by pilo1987

2023-08-18 13:31 UTC, huascraft approved these changes

2023-08-18 16:48 UTC, Ramir0 requested changes

2023-08-18 16:48 UTC, Ramir0 commented on README.md
> +- Go back to the main project folder, open the **cqrs-user-command-service** folder, eject the following command:
use the word "run" instead of "eject"

2023-08-18 16:48 UTC, Ramir0 commented on README.md
> +- When running the two projects (command, query) the port 8081 and 8082 appears without error in the editor console we can say that everything is fine.
before this step, it should be useful to add two steps:
- Open the project folder in your preferred IDE 
- Run both projects using as the gradle task or following your preferred IDE default run process

2023-08-23 16:22 UTC, Ramir0 approved these changes

2023-08-24 20:53 UTC, merged